/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
SPDX-License-Identifier: Apache-2.0
-/
import Mathlib.Data.Finset.Image
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Basic

/-!
# Finite relation fibers

The trace of one row of a heterogeneous binary relation on a supplied finite support, and
the finite family of traces generated by a finite set of rows. These are set-system objects:
no graph, model, regularity, or stability structure is assumed.

The support is explicit. This keeps the definitions useful on infinite ambient types and
makes the empty-support endpoint honest: every fiber on `∅` is `∅`, while a nonempty row
set generates the singleton family `{∅}`.
-/

namespace RegularityLemmata

section RelationFiber

variable {α β : Type*}

/-- The fiber of `R` at `a`, traced on the finite support `B`. -/
def fiber (R : α → β → Prop) [DecidableRel R] (a : α) (B : Finset β) : Finset β :=
  B.filter (R a)

@[simp] theorem mem_fiber (R : α → β → Prop) [DecidableRel R] (a : α) (B : Finset β)
    (b : β) : b ∈ fiber R a B ↔ b ∈ B ∧ R a b := by
  simp [fiber]

/-- A relation fiber is supported on the finite set on which it was traced. -/
theorem fiber_subset (R : α → β → Prop) [DecidableRel R] (a : α) (B : Finset β) :
    fiber R a B ⊆ B := by
  intro b hb
  exact (mem_fiber R a B b).1 hb |>.1

/-- Restricting the support can only shrink a fiber. -/
theorem fiber_mono (R : α → β → Prop) [DecidableRel R] (a : α)
    {B C : Finset β} (hBC : B ⊆ C) : fiber R a B ⊆ fiber R a C := by
  intro b hb
  rw [mem_fiber] at hb ⊢
  exact ⟨hBC hb.1, hb.2⟩

@[simp] theorem fiber_empty (R : α → β → Prop) [DecidableRel R] (a : α) :
    fiber R a ∅ = ∅ := by
  simp [fiber]

/-- Tracing on an intersection is the same as tracing first and then intersecting. -/
@[simp] theorem fiber_inter (R : α → β → Prop) [DecidableRel R] [DecidableEq β]
    (a : α) (B C : Finset β) : fiber R a (B ∩ C) = fiber R a B ∩ C := by
  ext b
  simp [fiber, and_assoc, and_comm]

/-- The family of fibers generated by rows in `A`, all traced on `B`. -/
def fiberFamily (R : α → β → Prop) [DecidableRel R] [DecidableEq β]
    (A : Finset α) (B : Finset β) : Finset (Finset β) :=
  A.image fun a => fiber R a B

@[simp] theorem mem_fiberFamily (R : α → β → Prop) [DecidableRel R] [DecidableEq β]
    (A : Finset α) (B : Finset β) (s : Finset β) :
    s ∈ fiberFamily R A B ↔ ∃ a ∈ A, fiber R a B = s := by
  simp [fiberFamily]

/-- Every member of a fiber family is supported on the tracing set. -/
theorem mem_fiberFamily_subset (R : α → β → Prop) [DecidableRel R] [DecidableEq β]
    (A : Finset α) (B : Finset β) {s : Finset β} (hs : s ∈ fiberFamily R A B) : s ⊆ B := by
  obtain ⟨a, _, rfl⟩ := (mem_fiberFamily R A B s).1 hs
  exact fiber_subset R a B

@[simp] theorem fiberFamily_empty_left (R : α → β → Prop) [DecidableRel R]
    [DecidableEq β] (B : Finset β) : fiberFamily R ∅ B = ∅ := by
  simp [fiberFamily]

/-- A nonempty row family traced on `∅` consists of the single fiber `∅`. -/
theorem fiberFamily_empty_right (R : α → β → Prop) [DecidableRel R]
    [DecidableEq β] {A : Finset α} (hA : A.Nonempty) : fiberFamily R A ∅ = {∅} := by
  simpa [fiberFamily, fiber] using (Finset.image_const hA (∅ : Finset β))

/-- Adding rows can only enlarge the represented fiber family. -/
theorem fiberFamily_mono_left (R : α → β → Prop) [DecidableRel R] [DecidableEq β]
    {A A' : Finset α} (hAA' : A ⊆ A') (B : Finset β) :
    fiberFamily R A B ⊆ fiberFamily R A' B := by
  intro s hs
  obtain ⟨a, ha, rfl⟩ := (mem_fiberFamily R A B s).1 hs
  exact (mem_fiberFamily R A' B _).2 ⟨a, hAA' ha, rfl⟩

end RelationFiber

/-! ### Executable endpoint tests -/

namespace RelationFiberTests

example : fiber (fun a : Fin 2 => fun b : Fin 3 => a.val = b.val) 1 Finset.univ = {1} := by
  decide

example :
    (fiberFamily (fun a : Fin 2 => fun b : Fin 3 => a.val = b.val)
      Finset.univ Finset.univ).card = 2 := by
  decide

example :
    fiberFamily (fun a : Fin 2 => fun b : Fin 3 => a.val = b.val) ({0} : Finset (Fin 2)) ∅ =
      {∅} := by
  decide

end RelationFiberTests

end RegularityLemmata
